### ISSUE TITLE
error running brew commands ie. `brew search gcc`

### ISSUE THREAD

**Issue by ipatch** [ipatch/brew#91]
### `brew doctor` output

```shell
na
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
na
```

### What were you trying to do (and why)?

run basic brew commands

### What happened (include all command output)?

na

### What did you expect to happen?

not to see a ruby backtrace

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew search gcc
```

---

output

```
Error: undefined method `parse' for class JSON::Ext::Parser
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/json-2.9.0/lib/json/common.rb:221:in `parse'
/home/capin/homebrew/Library/Homebrew/tap.rb:935:in `formula_renames'
/home/capin/homebrew/Library/Homebrew/tap.rb:1298:in `formula_renames'
/home/capin/homebrew/Library/Homebrew/formulary.rb:1146:in `tap_formula_name_type'
/home/capin/homebrew/Library/Homebrew/formulary.rb:751:in `try_new'
/home/capin/homebrew/Library/Homebrew/formulary.rb:808:in `try_new'
/home/capin/homebrew/Library/Homebrew/formulary.rb:1186:in `block in loader_for'
/home/capin/homebrew/Library/Homebrew/formulary.rb:1185:in `each'
/home/capin/homebrew/Library/Homebrew/formulary.rb:1185:in `loader_for'
/home/capin/homebrew/Library/Homebrew/formulary.rb:979:in `factory'
/home/capin/homebrew/Library/Homebrew/search.rb:72:in `block in search_formulae'
/home/capin/homebrew/Library/Homebrew/search.rb:72:in `map'
/home/capin/homebrew/Library/Homebrew/search.rb:72:in `search_formulae'
/home/capin/homebrew/Library/Homebrew/search.rb:129:in `search_names'
/home/capin/homebrew/Library/Homebrew/cmd/search.rb:81:in `run'
/home/capin/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```
```

**Comment by ipatch** [comment]
it appears i might running an older version of the portable ruby provided by homebrew

```
╰─λ l
total 8.0K
drwxrwxr-x 2 capin users 4.0K Nov 27 17:50 ./
drwxrwxr-x 5 capin users 4.0K Nov 18 15:42 ../
lrwxrwxrwx 1 capin users    5 Nov 23 14:43 current -> 3.3.6
```

```
╰─λ pwd
/home/capin/homebrew/Library/Homebrew/vendor/portable-ruby
```

**Comment by ipatch** [comment]
i ran into this issue again (today), and after removing the bundle directory (which i do not recommend). i restored it with

```
git checkout -- bundle/
```

then reran `brew style freecad/freecad -v` and that performed the below operation,

```
==> Installing 'bundler' gem
Fetching bundler-2.6.8.gem
Fetching gem metadata from https://rubygems.org/.......
```

**Comment by ipatch** [comment]
**fun fact** if you ever want to use homebrew's portable ruby when running brew commands prefix the command with,

```
HOMEBREW_FORCE_VENDOR_RUBY=1
```

ie.

```
HOMEBREW_FORCE_VENDOR_RUBY=1 brew style freecad/freecad
```

**Comment by ipatch** [comment]
ran into this issue again, ie. the below error message,

```
╰─λ brew -V
<internal:/home/capin/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.7/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require': linked to incompatible /home/capin/homebrew/Cellar/ruby/3.4.3/lib/libruby.so.3.4 - /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/json-2.16.0/lib/json/ext/parser.so (LoadError)
	from <internal:/home/capin/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.7/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
```

the fix,

```
╰─λ brew -v
Homebrew 5.0.4-46-g2d71360
Homebrew/homebrew-core (git revision 949d8798f80; last commit 2025-12-03)
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew (main ✔)
╰─λ cd /home/capin/homebrew/Library/Homebrew/vendor/bundle
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle (main ✔)
╰─λ l
total 0
drwxrwxr-x. 1 capin capin  22 Apr 12  2025 ./
drwxrwxr-x. 1 capin capin 296 Nov 18 11:41 ../
drwxrwxr-x. 1 capin capin  16 Dec  1 12:22 bundler/
drwxrwxr-x. 1 capin capin  60 Oct 19 14:59 ruby/
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle (main ✔)
╰─λ cd bundler/
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/bundler (main ✔)
╰─λ l
total 12K
drwxrwxr-x. 1 capin capin  16 Dec  1 12:22 ./
drwxrwxr-x. 1 capin capin  22 Apr 12  2025 ../
-rw-rw-r--. 1 capin capin 11K Dec  1 12:22 setup.rb
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/bundler (main ✔)
╰─λ ..
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle (main ✔)
╰─λ l
total 0
drwxrwxr-x. 1 capin capin  22 Apr 12  2025 ./
drwxrwxr-x. 1 capin capin 296 Nov 18 11:41 ../
drwxrwxr-x. 1 capin capin  16 Dec  1 12:22 bundler/
drwxrwxr-x. 1 capin capin  60 Oct 19 14:59 ruby/
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle (main ✔)
╰─λ cd ruby/
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby (main ✔)
╰─λ l
total 4.0K
drwxrwxr-x. 1 capin capin  60 Oct 19 14:59 ./
drwxrwxr-x. 1 capin capin  22 Apr 12  2025 ../
drwxrwxr-x. 1 capin capin 160 Apr 12  2025 3.3.0/
drwxrwxr-x. 1 capin capin 160 Nov 19 11:18 3.4.0/
-rw-r--r--. 1 capin capin  24 Oct 19 14:59 .homebrew_gem_groups
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby (main ✔)
╰─λ cat .homebrew_gem_groups
audit
formula_test
style⏎
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby (main ✔)
╰─λ cd 3.4.0/
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0 (main ✔)
╰─λ l
total 4.0K
drwxrwxr-x. 1 capin capin  160 Nov 19 11:18 ./
drwxrwxr-x. 1 capin capin   60 Oct 19 14:59 ../
drwxrwxr-x. 1 capin capin  138 Nov  7 12:07 bin/
drwxrwxr-x. 1 capin capin    0 Apr 17  2025 build_info/
drwxrwxr-x. 1 capin capin 1.4K Nov 19 11:18 cache/
drwxrwxr-x. 1 capin capin    0 Sep 30 13:47 doc/
drwxrwxr-x. 1 capin capin   26 Apr 17  2025 extensions/
drwxrwxr-x. 1 capin capin 1.2K Dec  1 12:22 gems/
-rw-rw-r--. 1 capin capin    1 Apr 17  2025 .homebrew_vendor_version
drwxrwxr-x. 1 capin capin   28 Jun  5 13:54 plugins/
drwxrwxr-x. 1 capin capin 1.7K Nov 19 11:18 specifications/
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0 (main ✔)
╰─λ cd bin/
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/bin (main ✔)
╰─λ l
total 44K
drwxrwxr-x. 1 capin capin 138 Nov  7 12:07 ./
drwxrwxr-x. 1 capin capin 160 Nov 19 11:18 ../
-rwxr-xr-x. 1 capin capin 564 Apr 26  2025 bundle*
-rwxr-xr-x. 1 capin capin 566 Apr 26  2025 bundler*
-rwxr-xr-x. 1 capin capin 525 Jun  5 13:54 erb*
-rwxr-xr-x. 1 capin capin 525 Jun  5 13:54 irb*
-rwxr-xr-x. 1 capin capin 561 Nov  7 12:07 patchelf.rb*
-rwxr-xr-x. 1 capin capin 531 Sep 30 13:47 racc*
-rwxr-xr-x. 1 capin capin 531 Jun  5 13:54 rdoc*
-rwxr-xr-x. 1 capin capin 527 Jun  5 13:54 ri*
-rwxr-xr-x. 1 capin capin 549 Nov  7 12:07 rubocop*
-rwxr-xr-x. 1 capin capin 551 Nov  6 15:11 ruby-parse*
-rwxr-xr-x. 1 capin capin 555 Nov  6 15:11 ruby-rewrite*
╭─capin ssh m1mac in /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/bin (main ✔)
╰─λ ./bundle
```

ie.

```
cd /home/capin/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/bin
./bundle
```
